src/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "Thisisarandomstring"

    from src.views import views

    app.register_blueprint(views, url_prefix="/")

    return app

src/views.py
from flask import Blueprint, render_template, redirect, request, url_for
from src.backend.benchmark import benchmark

views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
def index():
    return render_template("index.html")


@views.route("/sus", methods=["GET", "POST"])
def sus():
    if request.method == "POST":
        passwords = str(request.form.get("passwords"))
        pass_list = list(passwords.split(", "))

        results = benchmark(pass_list)
        return render_template("result.html", results=results)

    return render_template("sus.html")

src/templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}Susword{% endblock %}</title>
  </head>
  <body class="d-flex flex-column h-100">
    {% include 'navbar.html' %}
    <br/>
    <main class="flex-shrink-0">
      <div class = "container">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% block footer %}{% endblock %}

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% block content %}
<br>
<h1>Welcome to Susword!</h1>

{% endblock %}

{% block footer %}
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <p>Made by:</p>
    <ul>
      <li>Bryn Abyan Ghiffar - 2502087263</li>
      <li>Jason Jeremy Wijadi - 2440077301</li>
      <li>Monique Senjaya - 2440061285 </li>
      <li>Christopher Tendi - 2440065030 </li>
    </ul>
  </div>
</footer>
{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    {# Title text #}
    <a class="navbar-brand" href="{{url_for('views.index')}}">Susword</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {# Sus button #}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('views.sus')}}">Sus</a>
        </li>
        {# Register button #}
        <li class="nav-item">
          {# <a class="nav-link" href="{{url_for('views.register')}}">Register</a> #}
        </li>
      </ul>
    </div>
  </div>
</nav>

src/templates/result.html
{% extends 'base.html' %}
{% block title %}
Susword - Result
{% endblock %}

{% block content %}
<h1>AES encryption: {{results[0][0]}}</h1>
<h1>AES decryption: {{results[0][1]}}</h1>
<br/>
<h1>DES encryption: {{results[1][0]}}</h1>
<h1>DES decryption: {{results[1][1]}}</h1>
<br/>
<h1>RSA encryption: {{results[2][0]}}</h1>
<h1>RSA decryption: {{results[2][1]}}</h1>

{% endblock %}

src/templates/sus.html
{% extends 'base.html' %}
{% block title %}
Susword - Sus
{% endblock %}

{% block content %}
<h1>Sus your passwords here!</h1>
<br/>
<form method="post">
  <div class="form-group">
    <label for="password">Passwords (comma separated)</label>
    <input type="text" class="form-control" id="passwords" name="passwords" placeholder="Enter your passwords"/>
  </div>
  <br/>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}